#9 Daemon production build

diff --git a/services/daemon/Dockerfile b/services/daemon/Dockerfile
--- a/services/daemon/Dockerfile
+++ b/services/daemon/Dockerfile
@@ -15,9 +15,6 @@
 
 FROM node:10.14-alpine AS builder
 
-# Pass arguments down to the webpack builder to substitute variables
-ARG REACT_APP_NAME
-
 # NPM Install for building
 WORKDIR /usr/src/app-build
 ADD package.json /usr/src/app-build/package.json
@@ -32,25 +29,24 @@ RUN yarn install --production=true
 # Copy source files:
 WORKDIR /usr/src/app-build
 ADD index.js /usr/src/app-build
+ADD index.dev.js /usr/src/app-build
 ADD .babelrc /usr/src/app-build
-ADD .env /usr/src/app-build/.env
-ADD .eslintrc /usr/src/app-build/.eslintrc
-ADD .eslintignore /usr/src/app-build/.eslintignore
-ADD webpack.config.extend.js /usr/src/app-build
-ADD webpackDevServer.config.extend.js /usr/src/app-build
-ADD react-intl-pack.js /usr/src/app-build
+ADD .babelrc /usr/src/app-build
+ADD .env /usr/src/app-build
+ADD .eslintrc /usr/src/app-build
+ADD .eslintignore /usr/src/app-build
 
 # Build backend
 WORKDIR /usr/src/app-build
 ADD ssr /usr/src/app-build/ssr
-RUN npm run build:ssr
-
-# Build frontend
-WORKDIR /usr/src/app-build
-ADD src /usr/src/app-build/src
-RUN npm run build:src
-ADD public /usr/src/app-build/public
 RUN npm run build
+
+
+
+
+
+
+
 
 
 #
@@ -68,12 +64,79 @@ FROM node:10.14-alpine AS runner
 # Copy assets for build:
 WORKDIR /usr/src/app
 COPY --from=builder /usr/src/app-run/node_modules ./node_modules
-COPY --from=builder /usr/src/app-build/build ./build
-COPY --from=builder /usr/src/app-build/build-src ./build-src
+# COPY --from=builder /usr/src/app-build/build ./build
+# COPY --from=builder /usr/src/app-build/build-src ./build-src
 COPY --from=builder /usr/src/app-build/build-ssr ./build-ssr
 ADD package.json /usr/src/app
 ADD index.js /usr/src/app
 
-# Default environment configuration:
-EXPOSE 8080
-CMD node index.js
+
+
+
+
+
+
+
+#
+# Install Docker to get the logs out of the shit
+# -- This is needed only for MacOSX pourpose --
+#
+
+RUN apk add --no-cache \
+		ca-certificates
+
+# set up nsswitch.conf for Go's "netgo" implementation (which Docker explicitly uses)
+# - https://github.com/docker/docker-ce/blob/v17.09.0-ce/components/engine/hack/make.sh#L149
+# - https://github.com/golang/go/blob/go1.9.1/src/net/conf.go#L194-L275
+# - docker run --rm debian:stretch grep '^hosts:' /etc/nsswitch.conf
+RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
+
+ENV DOCKER_CHANNEL stable
+ENV DOCKER_VERSION 18.09.1
+# TODO ENV DOCKER_SHA256
+# https://github.com/docker/docker-ce/blob/5b073ee2cf564edee5adca05eee574142f7627bb/components/packaging/static/hash_files !!
+# (no SHA file artifacts on download.docker.com yet as of 2017-06-07 though)
+
+RUN set -eux; \
+	\
+# this "case" statement is generated via "update.sh"
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64) dockerArch='x86_64' ;; \
+		armhf) dockerArch='armel' ;; \
+		aarch64) dockerArch='aarch64' ;; \
+		ppc64le) dockerArch='ppc64le' ;; \
+		s390x) dockerArch='s390x' ;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	esac; \
+	\
+	if ! wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+		exit 1; \
+	fi; \
+	\
+	tar --extract \
+		--file docker.tgz \
+		--strip-components 1 \
+		--directory /usr/local/bin/ \
+	; \
+	rm docker.tgz; \
+	\
+	dockerd --version; \
+	docker --version
+
+
+
+
+
+
+#
+# Startup Info
+# ==========================================
+#
+
+ENV NODE_ENV production
+ENV BABEL_ENV node
+ENV LOG_LEVEL error
+
+ENTRYPOINT ["node", "index.js"]
